modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="endless_end"
version="1.0.0"
displayName="Endless End"
displayURL="https://prcrichards.wixsite.com/portfolio"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Mindthemoods"
description="And now I may rest."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.endless_end]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.endless_end]]
    modId="geckolib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.endless_end]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration