modLoader="javafml"
loaderVersion="[4,)"
license="Academic Free License v3.0"

[[mods]]
modId="endless_end"
version="1.0.0"
displayName="Endless End"
displayURL="https://prcrichards.wixsite.com/portfolio"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Mindthemoods"
description="And now I may rest."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.endless_end]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.endless_end]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"

[[dependencies.endless_end]]
modId="geckolib"
type="required"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.endless_end]]
modId="geckolib"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"


[[mixins]]
    config="mixins.endless_end.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration